version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    depends_on:
      - database
      - redis
      - jobs
    stdin_open: true
    tty: true
    networks:
      - network

  database:
    image: postgres:12.3
    env_file:
      - config/docker.env
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    driver: bridge

volumes:
  database_data:
